<?php

/**
 * @file
 * Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */

function drupalbook_preprocess_block($variables) {
  $test = 'asdf';
    if($variables['elements']['#id'] == 'block-heroonmainpage') {
    $variables['background_image_url'] = '';
    $url = file_create_url($variables['content'][block_content]=>field_background_image=>entity=>
    getFileUri());
    $variables['background_image_url'] = $url;
    }
  }
}
